name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Compute base path for GitHub Pages
        run: |
          REPO="${{ github.repository }}"
          NAME="${{ github.event.repository.name }}"
          if [[ "$REPO" == *.github.io* ]]; then
            echo "VITE_BASE_PATH=/" >> $GITHUB_ENV
          else
            echo "VITE_BASE_PATH=/$NAME/" >> $GITHUB_ENV
          fi

      - name: Build
        run: npm run build
        env:
          VITE_BASE_PATH: ${{ env.VITE_BASE_PATH }}

      - name: Add .nojekyll
        run: |
          touch ./dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
